# Generated by Django 3.0.6 on 2020-06-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'managed': True},
        ),
    ]
