# Generated by Django 3.0.6 on 2020-06-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_auto_20200602_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'managed': False},
        ),
    ]
