# Generated by Django 3.0.7 on 2020-06-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_auto_20200609_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'managed': True},
        ),
    ]
