# Generated by Django 3.0.6 on 2020-06-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_auto_20200602_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
