# Generated by Django 3.0.7 on 2020-06-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_auto_20200613_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
